displayName: Real IP
summary: Retrieve client IPs.
type: middleware
import: github.com/Desuuuu/traefik-real-ip-plugin

testData:
  retrievers:
    - header: X-Forwarded-For
      proxyCIDRs:
        - "203.0.113.195/24"
  headers:
    - X-Real-IP
