name: Test
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: [1.19, 1.21]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download dependencies
        run: go mod download
      - name: Test
        run: go test -v -race ./...
